vendor/src/github.com/docker/engine-api/client/errors.go
vendor/src/github.com/docker/engine-api/client/hijack.go

We are not really connecting to a Docker daemon now.
Also don't handcraft error code in postHijacked. Use the
predefined one.
Signed-off-by: Peng Tao <bergwolf@gmail.com>

Change connection failure message

---

integration-cli/issue/hyper_cli_inspect_experimental_test.go
integration-cli/issue/hyper_cli_start_test.go
integration-cli/issue/hyper_cli_stats_test.go

Move "hyper_cli_inspect_experimental_test.go","hyper_cli_start_test.go","hyper_cli_stats_test.go to issue".Totally we cannot pass four cases in all files.

mv *inspect_experimental*,*start*,*stats* to issue

---

api/client/exec.go
api/client/run.go

This PR adds support protocol (git, http and https) based volume mapping to `hyper run` command. For each protocol based volume, a new volume is created and filled in with contents pointed by the protocol URL.
http://
```
[lear@getdvm]$pkt run -d -v https://github.com/nginxinc/docker-nginx/raw/master/stable/alpine/Dockerfile:/data busybox
3326018a72d759141aa51136c5273260a4b4fef53107d66615128ef6af505165
[lear@getdvm]$pkt exec 3326018a72d759141aa51136c5273260a4b4fef53107d66615128ef6af505165 df
Filesystem           1K-blocks      Used Available Use% Mounted on
/dev/sdb              10190100     38080   9611348   0% /
devtmpfs                250552         0    250552   0% /dev
tmpfs                   253344         0    253344   0% /dev/shm
/dev/sda              10190100     36900   9612528 …
```

Init protocol based volume mapping in hyper run

---

api/client/fip.go
api/client/run.go
api/client/utils.go
vendor/src/github.com/dutchcoders/goftp/LICENSE
vendor/src/github.com/dutchcoders/goftp/README.md
vendor/src/github.com/dutchcoders/goftp/doc.go
vendor/src/github.com/dutchcoders/goftp/ftp.go
vendor/src/github.com/dutchcoders/goftp/ftp_test.go
vendor/src/github.com/dutchcoders/goftp/upload.go
vendor/src/github.com/satori/go.uuid/.travis.yml
vendor/src/github.com/satori/go.uuid/LICENSE
vendor/src/github.com/satori/go.uuid/README.md
vendor/src/github.com/satori/go.uuid/benchmarks_test.go
vendor/src/github.com/satori/go.uuid/uuid.go
vendor/src/github.com/satori/go.uuid/uuid_test.go

This is based on top of https://github.com/hyperhq/hypercli/pull/117 and adds local volume initialisation support.
User can use `hyper run -v /local/dir:/container/dir` to map a local file or directory to container.
_NOTE_: this will be broken with the incoming port mapping support. That is the reason I pushed this local volume support PR separate from original https://github.com/hyperhq/hypercli/pull/117 
Test results:
```
[lear@hyper-private]$zenlayer run -d -v /home/bergwolf/workplace/golang/src/github.com/bergwolf:/data busybox
0afc562a68be2a0cc8c5c9f18cfce3472cb8f7581d4cc33360611662b53b1f55
[lear@hyper-private]$zenlayer exec 0afc562a68be2a0cc8c5c9f18cfce3472cb8f7581d4cc33360611662b53b1f55 df
Filesystem           1K-blocks      Used Available Use% Mounted on
/dev/sda …
```

support initialize local volume mapping in hyper run

---

api/client/exec.go
api/client/run.go
api/client/utils.go

So that server can use the same file name to identify a file based volume, and mount it to a file in container instead of mounting its parent directory.
Needs https://github.com/hyperhq/hyperstart/pull/120
```
[lear@hyperstart]$mypkt run -d -v https://github.com/nginxinc/docker-nginx/raw/master/stable/alpine/Dockerfile:/data1 -v https://github.com/nginxinc/docker-nginx.git:/data2 busybox
6d6fb4dfc9bf38230424b7876d1f716169acc5551308783a20a0816261d8fa3c
[lear@hyperstart]$mypkt exec 6d6fb4dfc9bf38230424b7876d1f716169acc5551308783a20a0816261d8fa3c ls -la /data1 /data2
-rw-r--r--    1 root     root          4349 Jun 22 10:20 /data1
/data2:
total 24
drwxr-xr-x    5 root     root          4096 Jun 22 10:20 .
drwxr-xr-x   14 root     root          4096 Jun 22 10:20 ..
drwxr-xr-x    8 root …
```

Init file based volume with special file name

---

api/client/fip.go

Just noticed this typo while reading the [blog](https://blog.hyper.sh/learn-hyper_-by-examples-network-container.html) 😃

Small typo around container

---

api/client/run.go

So that we can use different label when we decide to use different
uploading mechanisms in future.

use hyperhq/volume_uploader v1 instead of latest

---

api/client/fip.go
vendor/src/github.com/docker/engine-api/client/fip.go
vendor/src/github.com/docker/engine-api/client/interface.go

```
[lei@h8s-single hypercli]$ pkt fip attach --help
Usage:	hyper fip attach [OPTIONS] FIP CONTAINER
Connects a container to a floating IP
--help             Print usage
[lei@h8s-single hypercli]$ pkt fip detach --help
Usage:	hyper fip detach [OPTIONS] CONTAINER
Disconnects container from a floating IP
--help             Print usage
[lei@h8s-single hypercli]$ pkt fip --help
Usage:	hyper fip [OPTIONS] COMMAND [OPTIONS]
Commands:
allocate                 Allocate a or some IPs
attach                   Attach floating IP to container
detach                   Detach floating IP from conainer
ls                       List all floating IPs
release                  Release a floating IP
Run 'hyper fip COMMAND --help' for more information on a command.
--help             Print usage
```

rename fip operation to attach/detach

---

integration-cli/future/api/hyper_api_volume_init_test.go
integration-cli/future/cli/hyper_cli_run_volume_init_test.go

Had to split the UTs into several files because otherwise they can easily run timeout(10 minutes max).

Add hyper run volume init tests 

---

integration-cli/passed/cli/hyper_cli_port_test.go

```
finish init
=== RUN   Test
INFO: Testing against a remote daemon(tcp://us-west-1.hyper.sh:443)
[2016-08-13 02:17:56] github.com/hyperhq/hypercli/integration-cli.(*DockerSuite).TestPortHostBinding - 5.238844 sec
[2016-08-13 02:18:06] github.com/hyperhq/hypercli/integration-cli.(*DockerSuite).TestPortList - 57.458524 sec
[2016-08-13 02:19:05] github.com/hyperhq/hypercli/integration-cli.(*DockerSuite).TestUnpublishedPortsInPsOutput - 18.594692 sec
OK: 3 passed
--- PASS: Test (92.31s)
PASS
ok  	github.com/hyperhq/hypercli/integration-cli	93.208s
```

modify port test cases

---

runconfig/opts/parse.go

If volume name is a single character, check next character to see if
it is a windows partition. If not, consider it to be a valid volume
name.
Test results:
```
[lear@blog-examples]$mypkt volume create --name f
f
[lear@blog-examples]$mypkt run -d -v f:/data busybox
236f16512fe2ff40173927096799fa41d12b7ebb62ba482394f451289eafe866
[lear@blog-examples]$mypkt volume ls
DRIVER              VOLUME NAME                                                       SIZE                CONTAINER
hyper               f                                                                 10 GB               236f16512fe2
[lear@blog-examples]$mypkt exec 236f16512fe2ff40173927096799fa41d12b7ebb62ba482394f451289eafe866 df
Filesystem           1K-blocks      Used Available Use% Mounted on
/dev/sdb …
```

fix volumeSplitN

---

runconfig/opts/parse.go

If specified, set container sh_hyper_noauto_volume=true label to tell server not to auto-create volumes specified in container image.

add create/run noauto volume option

---

integration-cli/future/cli/hyper_cli_run_noauto_volume_test.go

Test results:
```
⚡  /go/src/github.com/hyperhq/hypercli/integration-cli   noauto-test ●  go test
finish init
INFO: Testing against a remote daemon(tcp://147.75.195.37:6443)
[2016-09-14 03:21:21] github.com/hyperhq/hypercli/integration-cli.(*DockerSuite).TestImplicitOverwriteNoautoVolume - 28.870474 sec
[2016-09-14 03:22:12] github.com/hyperhq/hypercli/integration-cli.(*DockerSuite).TestNamedOverwriteNoautoVolume - 27.549756 sec
[2016-09-14 03:22:58] github.com/hyperhq/hypercli/integration-cli.(*DockerSuite).TestNoautoAndNormalVolume - 52.835125 sec
[2016-09-14 03:24:08] github.com/hyperhq/hypercli/integration-cli.(*DockerSuite).TestNoautoVolume - 27.693281 sec
[2016-09-14 03:25:12] github.com/hyperhq/hypercli/integration-cli.(*DockerSuite).TestVerifyNoautoVolumeBaseImage - 45.923531 …
```

add hyper run --noauto-volume tests

---

integration-cli/future/cli/hyper_cli_volume_populate_test.go

```
✘ ⚡  /go/src/github.com/hyperhq/hypercli/integration-cli   populate-test  go test
finish init
INFO: Testing against a remote daemon(tcp://147.75.195.37:6443)
[2016-09-13 07:09:52] github.com/hyperhq/hypercli/integration-cli.(*DockerSuite).TestPopulateImageVolume - 107.396555 sec
[2016-09-13 07:12:07] github.com/hyperhq/hypercli/integration-cli.(*DockerSuite).TestPopulateImplicitVolume - 22.246503 sec
[2016-09-13 07:12:46] github.com/hyperhq/hypercli/integration-cli.(*DockerSuite).TestPopulateMultiMountImplicitVolume - 27.165430 sec
[2016-09-13 07:13:30] github.com/hyperhq/hypercli/integration-cli.(*DockerSuite).TestPopulateMultiMountNamedVolume - 25.806369 sec
[2016-09-13 07:14:14] github.com/hyperhq/hypercli/integration-cli.(*DockerSuite).TestPopulateNamedImageVolume - 80.185182 …
```

add volume populate tests

---

api/client/cli.go

```
[lei@h8s-single hypercli]$ mv ~/.hyper/config.json /tmp/
[lei@h8s-single hypercli]$ cat ~/.hyper/config.json
cat: /home/lei/.hyper/config.json: No such file or directory
[lei@h8s-single hypercli]$ hyper/hyper ps
WARNING: null cloud config
Error response from daemon: Unauthorized
[lei@h8s-single hypercli]$ export HYPER_ACCESS=XXXXXXXXXXXXXXXXXXXXXXXXX
[lei@h8s-single hypercli]$ export HYPER_SECRET=XXXXXXXXXXXXXXXXXXXXXXXXX000000000000000000
[lei@h8s-single hypercli]$ hyper/hyper ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                              NAMES                 PUBLIC IP
[lei@h8s-single hypercli]$ unset HYPER_ACCESS
[lei@h8s-single hypercli]$ hyper/hyper ps -a
WARNING: null cloud config …
```

read from environment if the config.json is not existed

---

api/client/tarfile.go
api/client/volume.go

user might use hyper in some environment where a terminal is not available. Do not show volume upload progress bar in such case instead of failing hyper command.

Skip showing volume upload progress bar if no terminal

---

api/client/create.go
api/client/utils_unix.go
api/client/utils_windows.go
api/client/volume.go

For windows local volume, convert windows path to unix slash style and revert the result when uploading.
On Windows:
```
C:\bergwolf\workspace\src\github.com\hyperhq\hypercli\hyper>hyper.exe run -d -v
C:\bergwolf\workspace\src\github.com\hyperhq\hypercli\api\client:/data busybox
Sending client 71 / 71 [===========================================] 100.00% 4s
1645fe8a268e427a645bc93268bd4b38aa083aa3f8983c565d0f130c3fc18256
```
On Linux:
```
$hyper run -d -v `pwd`:/data busybox
Sending test-data 3 / 3 [==========================================] 100.00% 4s
e259eb73194f220c217d2742adb05c5a58bcc97697453031c1d55f8ac64bd91d
```
Fixes https://github.com/hyperhq/hypercli/issues/193

support windows local volume

---

api/client/compose.go
vendor/src/github.com/hyperhq/libcompose/docker/container.go
vendor/src/github.com/hyperhq/libcompose/project/context.go

```
[lei@h8s-single hypercli]$ pkt compose run test ping -c 2 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=55 time=3.401 ms
64 bytes from 8.8.8.8: seq=1 ttl=55 time=2.320 ms
--- 8.8.8.8 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 2.320/2.860/3.401 ms
[lei@h8s-single hypercli]$ echo $?
0
[lei@h8s-single hypercli]$ pkt compose run --rm test ping -c 2 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=55 time=3.212 ms
64 bytes from 8.8.8.8: seq=1 ttl=55 time=2.421 ms
--- 8.8.8.8 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 2.421/2.816/3.212 ms
INFO[0012] Project [hypercli]: Deleting project
INFO[0012] [0/1] [test]: …
```

fix compose run exit code issue

---

api/client/cli.go
api/client/formatter/custom.go
api/client/formatter/formatter.go
api/client/volume.go
cliconfig/config.go

```
[lei@h8s-single hypercli]$ hyper volume ls --format {{.Name}}
data
8bf2850f2d51231c8c9fc72a7afa5574cca7086f8a8ad96126b380cf600f885
bbaddb4be4c0a63f086f6b7019daa2218a271f4bdca5bd439061ceee6df2c56
test2
test1
[lei@h8s-single hypercli]$ hyper volume ls --format {{.Size}}
10 GB
10 GB
10 GB
10 GB
10 GB
[lei@h8s-single hypercli]$ hyper volume ls
DRIVER              NAME                                                              SIZE                CONTAINER
hyper               data                                                              10 GB
hyper               8bf2850f2d51231c8c9fc72a7afa5574cca7086f8a8ad96126b380cf600f885   10 GB               973772d1a02c4a747b1d1798a2accd0fb134d4a188ef6e61d0282851dabb7655
hyper …
```

add format option for hyper volume ls

---

integration-cli/README.md
integration-cli/docker_utils.go
integration-cli/hyper_cli_load_local_test.go
integration-cli/util.sh

```
[osboxes@osboxes integration-cli (integration-test ✗)]$ ./util.sh test
finish init
INFO: Testing against a remote daemon(tcp://147.75.195.39:6443)
[2017-06-06 09:31:12] github.com/hyperhq/hypercli/integration-cli.(*DockerSuite).TestLoadFromLocalCompressedArchive - 14.537943 sec
[2017-06-06 09:31:33] github.com/hyperhq/hypercli/integration-cli.(*DockerSuite).TestLoadFromLocalDocker - 7.754503 sec
[2017-06-06 09:31:47] github.com/hyperhq/hypercli/integration-cli.(*DockerSuite).TestLoadFromLocalMultipeImage - 1.364237 sec
----------------------------------------------------------------------
FAIL: hyper_cli_load_local_test.go:203: DockerSuite.TestLoadFromLocalMultipeImage
hyper_cli_load_local_test.go:220:
c.Assert(output, checker.Contains, "Loading multiple images from local is not …
```

add test case for load local

---

hack/generate-hyper-conf-qa.sh
integration-cli/README.md
integration-cli/check_test.go
integration-cli/docker_utils.go
integration-cli/hyper_cli_links_test.go
integration-cli/hyper_cli_logs_test.go
integration-cli/hyper_cli_ps_test.go
integration-cli/hyper_cli_restart_test.go
integration-cli/hyper_cli_run_test.go

```
$ hyper run -it --rm \
-e ACCESS_KEY="${HYPER_ACCESS_KEY}" \
-e SECRET_KEY="${HYPER_SECRET_KEY}" \
-e BRANCH="#225" \
hyperhq/hypercli-auto-test:qa go test -check.f "TestCli" -timeout 90m
INFO: clear resources(containers, images, snapshots, volumes, fips)
INFO: finish init
INFO: Testing against a remote daemon(tcp://us-west-1.hyper.sh:443)
[2017-06-23 13:49:53] github.com/hyperhq/hypercli/integration-cli.(*DockerSuite).TestCliConfigAndRewrite - 0.022833 sec
...
[2017-06-23 14:54:14] github.com/hyperhq/hypercli/integration-cli.(*DockerHubPullSuite).TestCliPullScratchNotAllowed - 0.059013 sec
OK: 231 passed, 19 skipped
PASS
ok      github.com/hyperhq/hypercli/integration-cli     3861.375s
```

Optimize integration test

---

api/client/cron.go
api/client/service.go

```
[lei@h8s-single hypercli]$ hyper/hyper load -i http://image-tarball.s3.amazonaws.com/test/public/ubuntu.tar.gz
Starting to download and load the image archive, please wait...
ubuntu:latest(sha256:2fa927b5cdd31cdec0027ff4f45ef4343795c7a2d19a9af4f32425132a222330) has been loaded.
[lei@h8s-single hypercli]$ hyper/hyper images
REPOSITORY                     TAG                 IMAGE ID            CREATED             SIZE
ubuntu                         latest              2fa927b5cdd3        12 months ago       122 MB
[lei@h8s-single hypercli]$ hyper/hyper cron create  --minute=*/5 --hour=* --name test-cron-job2 ubuntu ping -c 3 8.8.8.8
Cron test-cron-job2 is created.
[lei@h8s-single hypercli]$ hyper/hyper cron ls
Name                Schedule            Image               Command …
```

check image before pull image in cron and service

---

api/client/fip.go

typo (conainer) instead of container

Fix typo in hyper fip command help text

---

api/client/compose.go

In Windows.
When it runs `hyper compose` without "-p" option, current directory name is used as project name.
But in Windows, fullpath like "c:\foo\bar" is given as project name.
`path` always uses slash as path separator.
`filepath` uses appropriate path separator for system.

Raplace "path.Base" to "filePath.Base"

---

integration-cli/README.md
integration-cli/final/cli/hyper_cli_region_test.go
integration-cli/hyper_cli_config_test.go
integration-cli/util.sh

adjust integration test for cron job
```
#zl2 container test eu1
HYPER_ACCESS_KEY=xxx
HYPER_SECRET_KEY=xxx
APIROUTER="tcp://eu-central-1.hyper.sh:443"
REGION="eu-central-1"
BRANCH="#236"
hyper --region us-west-1 \
run -it --rm \
-e ACCESS_KEY="${HYPER_ACCESS_KEY}" \
-e SECRET_KEY="${HYPER_SECRET_KEY}" \
-e BRANCH=$BRANCH \
-e REGION="$REGION" \
-e DOCKER_HOST="${APIROUTER}" \
hyperhq/hypercli-auto-test:qa go test -check.f "TestCli.*Basic" -timeout 90m
#eu1 container test zl2
HYPER_ACCESS_KEY=xxx
HYPER_SECRET_KEY=xxx
APIROUTER="tcp://us-west-1.hyper.sh:443"
REGION="us-west-1"
BRANCH="#236"
hyper --region eu-west-1 \
run -it --rm \
-e ACCESS_KEY="${HYPER_ACCESS_KEY}" \
-e SECRET_KEY="${HYPER_SECRET_KEY}" \
-e BRANCH=$BRANCH \
-e REGION="$REGION" \
-e DOCKER_HOST="${APIROUTER}" \ …
```

fix test case

---

api/client/func.go

Just spotted it in the help pages

Update func.go for a typo

---

api/client/func.go

Use `ISO 8601` time format and generate the time string from UTC time instead of local time.

Fix time in func logs
