api/client/info.go

Signed-off-by: Crazykev <crazykev@zju.edu.cn>

info command, move feature warning to debug mode

---

api/client/volume.go
vendor/src/github.com/docker/engine-api/client/image_build.go
vendor/src/github.com/docker/engine-api/types/client.go
vendor/src/github.com/docker/engine-api/types/types.go

```
[lei@h8s-single hypercli]$ ./hyper/hyper --host=tcp://147.75.195.39:6443 volume ls
DRIVER              VOLUME NAME                                                        SIZE                CONTAINER
hyper               999e5bd66ab2c80171b063d8994aed75ae180206ba4eff4f04bd91e340482513   10 GB
hyper               0e79195cd4bffc4c7eeba6df877d05659c25bc142ab48e654f0bf6496af66602   1 GB
hyper               pt-test                                                            16 GB
hyper               98d9ac283a964468de6e976304117f4cc315c938387ed547682ae867c0266c60   10 GB
hyper               8b2883140b505b195da6c948a5d9f04f201033504536bd270b17bce1bc5e9461   10 GB
```

volume ls output enhancement

---

vendor/src/github.com/docker/engine-api/client/container_remove.go

fix https://github.com/hyperhq/hypercli/issues/17

fix remove non-exist container panic

---

integration-cli/passed/cli/hyper_cli_rename_test.go

Test passed, move it to pass directory.
Signed-off-by: Crazykev <crazykev@zju.edu.cn>

modify rename test case and move it to passed

---

integration-cli/issue/docker_cli_exec_unix_test.go

mv docker_cli_exec_unix_test.go to issue and add the required funcs. 
Signed-off-by: xlgao-zju <xlgao@zju.edu.cn>

mv docker_cli_exec_unix_test.go to issue

---

integration-cli/passed/hyper_cli_login_test.go

Signed-off-by: Crazykev <crazykev@zju.edu.cn>

move login test to passed

---

integration-cli/passed/cli/hyper_cli_inspect_test.go

The test of whole file may exceed 600s.But we can pass every case indeed.

mv docker_cli_inspect_test.go to passed

---

integration-cli/passed/cli/hyper_cli_exec_test.go

Add this test case, cause we fixed #24 .

add ExecIds test case

---

runconfig/opts/parse.go

Signed-off-by: Xu Wang <gnawux@gmail.com>

Enable the `-env-file` option for hyper run

---

integration-cli/passed/cli/hyper_cli_volume_test.go

The cases are all passed, but there are still two problems,some operation about volume sometimes may encounter "internal errors", but try several times, it will work。And the cases about "ls -f" are commented, and I think it's not a big deal.

mv docker_cli_volume_test.go to passed

---

integration-cli/README.md
integration-cli/passed/cli/hyper_cli_help_test.go

mv hyper_cli_help_test.go to passed

---

integration-cli/README.md
integration-cli/passed/cli/hyper_cli_search_test.go

mv hyper_cli_search_test.go to passed

---

api/client/snapshot.go

add some missing 's' in "hyper snapshot" help manual

add the missing 's' in Usage:hyper snaphot [OPTIONS] [COMMAND]

---

integration-cli/docker_cli_fip_test.go
integration-cli/docker_utils.go

[done]Cli fip test

---

integration-cli/README.md
integration-cli/passed/cli/hyper_cli_history_test.go

mv hyper_cli_history_test.go to passed

---

integration-cli/README.md
integration-cli/passed/cli/hyper_cli_ps_test.go

mv hyper_cli_ps_test.go to passed

---

integration-cli/README.md
integration-cli/issue/hyper_cli_logs_test.go
integration-cli/passed/cli/hyper_cli_logs_test.go

mv hyper_cli_logs_test.go to issue

---

integration-cli/issue/hyper_cli_restart_test.go

Wait util #14 and #43 fixed.
Signed-off-by: Crazykev <crazykev@zju.edu.cn>

move restart test case to issue

---

integration-cli/issue/docker_cli_attach_test.go
integration-cli/issue/docker_cli_attach_unix_test.go
integration-cli/passed/cli/hyper_cli_inspect_experimental_test.go

It is so sad that we cannot pass any case, but everything seems OK by hand ? so confusing.

mv *attach* to issue and mv hyper_cli_inspect_experimental_test.go to passed

---

integration-cli/passed/cli/hyper_cli_logs_test.go

mv hyper_cli_logs_test.go to pass

---

integration-cli/passed/api/hyper_api_exec_resize_test.go

mv hyper_api_exec_resize_test.go to passed

---

integration-cli/future/api/hyper_api_images_test.go
integration-cli/passed/api/hyper_api_images_test.go

[ready to review] mv hyper_api_images_test.go to passed and future

---

integration-cli/passed/api/hyper_api_logs_test.go

[ready to review]mv hyper_api_logs_test.go to passed

---

integration-cli/README.md

[ready to review] update readme

---

integration-cli/passed/cli/hyper_cli_search_test.go

fix typo in search test

---

integration-cli/hyper_api_fip_test.go
integration-cli/passed/api/hyper_api_fip_test.go

need to fix #98, before we merge this pr

add api-fip-test

---

api/client/run.go
api/client/volume.go
vendor/src/github.com/docker/engine-api/client/interface.go
vendor/src/github.com/docker/engine-api/client/volume_init.go
vendor/src/github.com/docker/engine-api/types/types.go

The PR adds a sub command `hyper volume init [source:volume]` that initialize a volume with a specified source.

Volume init cmd

---

api/client/volume.go

1. should pass slice reference instead of value to uploadLocalVolume()
2. should check http response code instead of only http connection errors.
Test results:
1. capture connection errors:
```
[lear@master]$mypkt run -d -v /home/bergwolf/foo/:/data busybox
uploading /home/bergwolf/foo/ Upload local volume failed: Post http://192.168.214.152/data0?cookie=fakecookie: dial tcp 192.168.214.152:80: getsockopt: connection refused
hyper: Post http://192.168.214.152/data0?cookie=fakecookie: dial tcp 192.168.214.152:80: getsockopt: connection refused.
See 'hyper run --help'.
```
2. capture returned server errors
```
[lear@master]$mypkt run -d -v /home/bergwolf/foo/:/data busybox
uploading /home/bergwolf/foo/ Upload local volume failed: Not Acceptable:I'd like to make it fail
hyper: Not …
```

fix volume upload error checking

---

api/client/create.go
api/client/run.go

One can use `hyper create -v` to create new container with local and remote volumes.
Test results:
```
[lear@compose]$hyper create -v https://raw.githubusercontent.com/msanand/docker-workflow/master/node/Dockerfile:/vol/data1 -v https://github.com/msanand/docker-workflow.git:/vol/data2 -v /home/bergwolf/demo/:/vol/data3 -v /home/bergwolf/tests/wait.c:/vol/data4 busybox
uploading /home/bergwolf/demo/ uploading /home/bergwolf/tests/wait.c .success
.......success
8b2983a71fe7de509593f792d6affa3c6a2f40d6d2d9a5422c700a22f0b4710b
[lear@compose]$hyper start 8b2983a71fe7de509593f792d6affa3c6a2f40d6d2d9a5422c700a22f0b4710b
8b2983a71fe7de509593f792d6affa3c6a2f40d6d2d9a5422c700a22f0b4710b
[lear@compose]$hyper exec 8b2983a71fe7de509593f792d6affa3c6a2f40d6d2d9a5422c700a22f0b4710b ls -l /vol/data1 …
```

enable create -v initialize volumes

---

api/client/fip.go

```
[lei@h8s-single hypercli]$ hyper/hyper fip allocate 1
Please note that Floating IP (FIP) is billed monthly. The billing begins when a new IP is allocated, ends when it is released. Partial month is treated as a entire month. Do you want to continue? [y/n]: n
[lei@h8s-single hypercli]$ hyper/hyper fip allocate 1
Please note that Floating IP (FIP) is billed monthly. The billing begins when a new IP is allocated, ends when it is released. Partial month is treated as a entire month. Do you want to continue? [y/n]: y
Error response from daemon: No more quota for use, please delete some, or apply more
[lei@h8s-single hypercli]$
```

prompt warning message on allocating new FIP

---

api/client/service.go

Pull image for service

---

contrib/completion/bash/hyper

Signed-off-by: Yao Zengzeng <yaozengzeng@zju.edu.cn>

support core command and global option completion

---

contrib/completion/bash/hyper

`hyper attach`
`hyper compose`
`hyper config`
`hyper create`
`hyper cron` 
`hyper exec`
`hyper fip`
`hyper history`
`hyper images`
`hyper info`
`hyper inspect` 
`hyper kill`
`hyper load`
`hyper login`
`hyper logout`
`hyper logs`
`hyper port`
`hyper ps`
`hyper pull`
`hyper rename`
`hyper restart`
`hyper rm`
`hyper rmi`
`hyper run` 
`hyper search`
`hyper service`
`hyper sg`
`hyper snapshot`
`hyper start`
`hyper stats`
`hyper stop`
`hyper update`
`hyper version`
`hyper volume`

Completion

---

runconfig/opts/parse.go

enable volumesfrom

---

api/client/volume.go

We do not allow users to set any volume driver options.

drop volume create driver options
